#!/bin/bash

# ExJAM Registration System - Service Account Setup Script

echo "🔐 ExJAM Registration System - Service Account Setup"
echo "====================================================="
echo ""

# Check if we're in the right directory
if [ ! -f "appsscript.json" ]; then
    echo "❌ Error: Please run this script from the google-apps-script directory"
    echo "   Current directory: $(pwd)"
    echo "   Expected files: appsscript.json, ExjamRegistrationSystem.gs"
    exit 1
fi

echo "✅ Found Apps Script project directory"
echo ""

# Display setup options
echo "🚀 Choose your service account setup option:"
echo ""
echo "1. 📋 View setup requirements and checklist"
echo "2. 🔧 Quick setup guide (step-by-step)"
echo "3. 📚 View detailed documentation"
echo "4. 🧪 Test service account functions (after setup)"
echo "5. 🚀 Deploy with service account (after setup)"
echo ""

read -p "Enter your choice (1-5): " choice

case $choice in
    1)
        echo ""
        echo "📋 Service Account Setup Requirements"
        echo "===================================="
        echo ""
        echo "✅ Prerequisites:"
        echo "   - Google Cloud Console access"
        echo "   - Google Apps Script project"
        echo "   - Administrative permissions"
        echo ""
        echo "📋 Setup Checklist:"
        echo "   ☐ Create Google Cloud Project"
        echo "   ☐ Enable required APIs"
        echo "   ☐ Create service account"
        echo "   ☐ Assign IAM roles"
        echo "   ☐ Download JSON key"
        echo "   ☐ Configure Apps Script"
        echo "   ☐ Test authentication"
        echo "   ☐ Deploy web app"
        echo ""
        echo "🔗 Required APIs:"
        echo "   - Google Drive API"
        echo "   - Google Sheets API"
        echo "   - Gmail API"
        echo "   - Google Forms API"
        echo "   - Google Apps Script API"
        echo ""
        ;;
    2)
        echo ""
        echo "🔧 Quick Service Account Setup Guide"
        echo "===================================="
        echo ""
        echo "📋 Step 1: Google Cloud Console"
        echo "   1. Go to console.cloud.google.com"
        echo "   2. Create project: 'exjam-registration-system'"
        echo "   3. Enable required APIs (see option 1)"
        echo ""
        echo "📋 Step 2: Create Service Account"
        echo "   1. Go to APIs & Services → Credentials"
        echo "   2. Click 'Create Credentials' → 'Service Account'"
        echo "   3. Name: 'exjam-registration-service'"
        echo "   4. Description: 'Service account for ExJAM registration system'"
        echo ""
        echo "📋 Step 3: Assign Roles"
        echo "   1. Click 'Select a role'"
        echo "   2. Choose 'Apps Script Admin'"
        echo "   3. Choose 'Project Editor'"
        echo "   4. Add your email as service account user"
        echo ""
        echo "📋 Step 4: Download Key"
        echo "   1. Click on service account"
        echo "   2. Go to 'Keys' tab"
        echo "   3. Click 'Add Key' → 'Create new key'"
        echo "   4. Choose 'JSON' format"
        echo "   5. Download and secure the file"
        echo ""
        echo "📋 Step 5: Configure Apps Script"
        echo "   1. Open your Apps Script project"
        echo "   2. Add service account email to CONFIG"
        echo "   3. Test with testServiceAccountAccess()"
        echo ""
        ;;
    3)
        echo ""
        echo "📚 Detailed Documentation"
        echo "========================="
        echo ""
        echo "📖 Complete setup guide: SERVICE_ACCOUNT_SETUP.md"
        echo "📖 Web app deployment: WEB_APP_DEPLOYMENT_GUIDE.md"
        echo "📖 System summary: WEB_APP_SUMMARY.md"
        echo ""
        echo "🔗 Key files to review:"
        echo "   - SERVICE_ACCOUNT_SETUP.md (this guide)"
        echo "   - WEB_APP_DEPLOYMENT_GUIDE.md (deployment)"
        echo "   - WEB_APP_SUMMARY.md (overview)"
        echo ""
        echo "💡 Pro tip: Read SERVICE_ACCOUNT_SETUP.md first for complete instructions"
        echo ""
        ;;
    4)
        echo ""
        echo "🧪 Test Service Account Functions"
        echo "================================"
        echo ""
        echo "📋 To test your service account setup:"
        echo ""
        echo "1. Open your Apps Script project at script.google.com"
        echo "2. Run this function:"
        echo "   testServiceAccountAccess()"
        echo ""
        echo "3. Check the execution log for:"
        echo "   ✅ Drive access: [folder name]"
        echo "   ✅ Sheets access: Available"
        echo "   ✅ Gmail access: Available"
        echo "   🎉 Service account access test passed!"
        echo ""
        echo "⚠️  Make sure you've completed the setup first!"
        echo ""
        ;;
    5)
        echo ""
        echo "🚀 Deploy with Service Account"
        echo "=============================="
        echo ""
        echo "📋 To deploy your web app with service account:"
        echo ""
        echo "1. Open your Apps Script project at script.google.com"
        echo "2. Run this function:"
        echo "   deployCompleteSystemWithServiceAccount()"
        echo ""
        echo "3. This will:"
        echo "   🔐 Test service account authentication"
        echo "   📋 Initialize registration system"
        echo "   🌐 Deploy web app with service account"
        echo "   🧪 Test complete system"
        echo ""
        echo "⚠️  Make sure service account is set up and tested first!"
        echo ""
        ;;
    *)
        echo "❌ Invalid choice. Please select 1-5."
        exit 1
        ;;
esac

echo "🎉 Service account setup information provided!"
echo ""
echo "📞 Next steps:"
echo "   1. Follow the setup guide in SERVICE_ACCOUNT_SETUP.md"
echo "   2. Test your setup with testServiceAccountAccess()"
echo "   3. Deploy with deployCompleteSystemWithServiceAccount()"
echo ""
echo "🔐 Your ExJAM registration system will have enterprise-grade security!"
